---
title: "Introduction to osmprob"
author: "Andreas Petutschnig"
date: "`r Sys.Date()`"
output:
    html_document:
        toc: true
        number_sections: true
        theme: journal
link-citations: true

abstract: "When using routing algorithms to model movement on a graph, one is not necessarily interested in obtaining the least-cost, but the most
realistic results. The average path between any two points is likely never the shortest, yet there is currently no way to estimate the course or
lengths of realistic paths. Instead, movement is often assumed to be singular and repeatable.  **osmprob** is an *R* library that provides
routing probabilities along all possible paths between any two points.  The path of highest probability is the shortest, yet all edges will
generally have non-zero probabilities of being traversed.  Importantly, the resultant network enables calculation of the probabalistically most
likely distance travelled between any two points. The package comes with a built-in **Shiny** **Leaflet** application to display the results in
a matter that is both understandable and visually pleasing."

keywords: routing, planning, OpenStreetMap

vignette: >
  %\VignetteIndexEntry{osmprob}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
bibliography: osmprob-refs.bib
---

# Introduction

This package allows users to calculate traversal probabilities and the estimated travel distance between two points on a graph based on the
methods introduced in @saerens2009randomized. It also contains methods that simplify the process of downloading and preprocessing
OpeneStreetMap[^1] road data on which the routing can be performed. This step also includes weighting the edges according to a specified means
of transport. The values used for weighting are derived from the Routino weighting profiles[^2].  Finally, the results can be visualised with
built-in mapping functions.

## Nomenclature

"**path** `noun | \ˈpath, ˈpäth\` [...] a sequence of arcs in a network that can be traced continuously without retracing any arc"  @mwPath

"**route** `noun | \ˈrüt, ˈrau̇t\` [...] an established or selected course of travel or action"  @mwRoute

Usually, the results produced by routing software like implementations of Dijkstra's algorithm (@dijkstra1959note) are least-cost edge sequences
called paths or routes.  It is important to clarify that the routing results produced by this software are not paths, but a set of traversal
probabilities of all edges on the graph. For lack of more fitting terminology, they will be referred to as routes in this paper.

# Methods

# Usage

The only input needed to download street data are the coordinates of the start and end points on the graph. The `download_graph` function builds
a bounding box including an optional buffer around the points and downloads all OpenStreetMap data tagged as `key = highway`[^3] in it.

```{r eval=FALSE}
devtools::load_all (export_all = FALSE)
start_pt <- c (11.58, 48.14)
end_pt <- c (11.585, 48.145)
graph <- download_graph (start_pt, end_pt)
route_start <- graph$compact$from_id [1]
route_end <- graph$compact$to_id [600]
path <- get_shortest_path (graph, route_start, route_end)
prob <- get_probability (graph, route_start, route_end, eta = 1)
plot_map (prob, path)
```

# Results

## Routing probabilities

## Speed

## Comparison with shortest path solutions

# Discussion and outlook

# References

[^1]: http://www.openstreetmap.org/
[^2]: https://www.routino.org/xml/routino-profiles.xml
[^3]: http://wiki.openstreetmap.org/wiki/Key:highway
