// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// makeCompactGraph
Rcpp::DataFrame makeCompactGraph(Rcpp::DataFrame graph);
RcppExport SEXP osmprob_makeCompactGraph(SEXP graphSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type graph(graphSEXP);
    rcpp_result_gen = Rcpp::wrap(makeCompactGraph(graph));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_lines_as_network
Rcpp::List rcpp_lines_as_network(const Rcpp::List& sf_lines, Rcpp::DataFrame pr);
RcppExport SEXP osmprob_rcpp_lines_as_network(SEXP sf_linesSEXP, SEXP prSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type sf_lines(sf_linesSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type pr(prSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_lines_as_network(sf_lines, pr));
    return rcpp_result_gen;
END_RCPP
}
// dijkstra
void dijkstra(Rcpp::DataFrame graph, long long start, long long end);
RcppExport SEXP osmprob_dijkstra(SEXP graphSEXP, SEXP startSEXP, SEXP endSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type graph(graphSEXP);
    Rcpp::traits::input_parameter< long long >::type start(startSEXP);
    Rcpp::traits::input_parameter< long long >::type end(endSEXP);
    dijkstra(graph, start, end);
    return R_NilValue;
END_RCPP
}
// rcpp_router
void rcpp_router(Rcpp::DataFrame netdf, int start_nodei, int end_nodei, double eta);
RcppExport SEXP osmprob_rcpp_router(SEXP netdfSEXP, SEXP start_nodeiSEXP, SEXP end_nodeiSEXP, SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type netdf(netdfSEXP);
    Rcpp::traits::input_parameter< int >::type start_nodei(start_nodeiSEXP);
    Rcpp::traits::input_parameter< int >::type end_nodei(end_nodeiSEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    rcpp_router(netdf, start_nodei, end_nodei, eta);
    return R_NilValue;
END_RCPP
}
