// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// makeCompactGraph
Rcpp::DataFrame makeCompactGraph(Rcpp::DataFrame graph);
RcppExport SEXP osmprob_makeCompactGraph(SEXP graphSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type graph(graphSEXP);
    rcpp_result_gen = Rcpp::wrap(makeCompactGraph(graph));
    return rcpp_result_gen;
END_RCPP
}
