# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' getDist
#'
#' Calculates the total distance in km between all sequential points in xAll
#' and yAll
#'
#' @param xAll vector containing all latitudes sequentially
#' @param yAll vector containing all longitudes sequentially
#' @return the total distance between a and b in km
getDist <- function(xAll, yAll) {
    .Call('osmprob_getDist', PACKAGE = 'osmprob', xAll, yAll)
}

#' makeCompactGraph
#'
#' Removes nodes and edges from a graph that are not needed for routing
#'
#' @param graph graph to be processed
#' @return Rcpp::DataFrame containing the output graph
makeCompactGraph <- function(graph) {
    .Call('osmprob_makeCompactGraph', PACKAGE = 'osmprob', graph)
}

